language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t votruk/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true votruk/react-test npm test 

after_success:
    - docker build -t votruk/multi-client ./client
    - docker build -t votruk/multi-nginx ./nginx
    - docker build -t votruk/multi-server ./server
    - docker build -t votruk/multi-worker ./worker

    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
    
    # Take those images and push them to doccker hub
    - docker push votruk/multi-client
    - docker push votruk/multi-nginx 
    - docker push votruk/multi-server
    - docker push votruk/multi-worker